name: Build and Deploy to Github Pages

on:
  workflow_run:
    workflows: [Run Tests]
    types: [completed]
    branches: [main]

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 21
          cache: npm

      - name: Install depedencies
        run: npm ci
      
      - name: Run build
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: "./dist"
  
  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2