name: main workflow

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 21
          cache: npm

      - name: Install depedencies
        run: npm ci
      
      - name: Run tests
        run: npm run test
